apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: wafer-train-pipeline
spec:
  tasks:
    - name: raw-train-data-validation
      taskRef:
        name: raw-train-data-validation-task

    - name: data-transform-train
      taskRef:
        name: data-transform-train-task
      runAfter:
        - raw-train-data-validation

    - name: db-operation-train
      taskRef:
        name: db-operation-train-task
      runAfter:
        - data-transform-train

    - name: preprocessing-train
      taskRef:
        name: preprocessing-train-task
      runAfter:
        - db-operation-train

    - name: clustering
      taskRef:
        name: clustering-task
      runAfter:
        - preprocessing-train

    - name: model-training
      taskRef:
        name: model-training-task
      runAfter:
        - clustering

    - name: load-prod-model
      taskRef:
        name: load-prod-model-task
      runAfter:
        - model-training
