apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: wafer_application
  name: wafer_application
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wafer_application
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: wafer_application
    spec:
      containers:
        image: 347460842118.dkr.ecr.us-east-1.amazonaws.com/wafer_application:
        name: wafer_application
status: {}
---
apiVersion: v1
kind: Service
metadata:
  name: lb-service
  labels:
    app: lb-service
spec:
  type: LoadBalancer
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: wafer_application
