apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: wafer-test-pipeline
spec:
  tasks:
    - name: raw-train-data-validation
      taskRef:
        name: raw-train-data-validation-task

    - name: data-transform-train
      taskRef:
        name: data-transform-train-task
      runAfter:
        - raw-train-data-validation