apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: db-operation-train-task
spec:
  steps:
    - name: db-operation-train-task
      image: 347460842118.dkr.ecr.us-east-1.amazonaws.com/wafer_db_operation_train:latest
